const paragraphs = {
    marsigliesi:{
        title:"Tegole Marsigliesi",
        text:"Le tegole marsigliesi sono la soluzione definitiva per chi cerca durata, funzionalità ed estetica per il proprio tetto. Nate nella storica regione di Marsiglia, queste tegole hanno dimostrato nel tempo di essere una scelta ineguagliabile. La loro forma ondulata garantisce un perfetto deflusso dell'acqua piovana, mentre la loro struttura resistente le rende ideali contro venti forti e condizioni meteorologiche avverse. La caratteristica tonalità rossastra, ottenuta grazie alla cottura in forni tradizionali, conferisce un tocco di classe a qualsiasi edificio. Ma non fermiamoci all'aspetto: investire in tegole marsigliesi significa garantire al proprio tetto una protezione che può durare oltre un secolo. Il nostro servizio offre l'installazione di queste tegole con la massima professionalità, assicurando una posa in opera perfetta e una manutenzione minima nel tempo. Scegliendo le tegole marsigliesi, scegli la qualità."
    },
    portoghesi:{
        title:"Tegole Portoghesi",
        text:"Le tegole portoghesi sono la sintesi perfetta tra design classico e tecnologia avanzata. Queste tegole, con le loro curve morbide e distintive, sono un omaggio alla tradizione architettonica del Portogallo, ma con una qualità costruttiva moderna che le rende ideali per le sfide di oggi. Ogni tegola è progettata per garantire un'ottima tenuta all'acqua e una protezione superiore contro gli elementi. La loro struttura compatta e la finitura lucida non solo migliorano l'aspetto estetico del tetto, ma offrono anche una durata e una resistenza ineguagliabili. Il colore ricco e profondo delle tegole portoghesi può trasformare qualsiasi edificio, conferendogli un'aura di eleganza e sofisticatezza. E quando si tratta di installazione, il nostro team di esperti garantisce precisione e attenzione ai dettagli, assicurando che ogni tegola sia posizionata alla perfezione. Con le tegole portoghesi, ottenete un tetto che parla di storia, ma è costruito per durare nel futuro."
    },
    coibentati:{
        title:"Pannelli Coibentati",
        text:"Nell'era dell'edilizia sostenibile e dell'efficienza energetica, i pannelli coibentati rappresentano una soluzione all'avanguardia per garantire un isolamento termico ottimale. Questi pannelli, composti da materiali isolanti di alta qualità inseriti tra due strati protettivi, offrono una barriera impenetrabile contro il freddo invernale e il calore estivo. Oltre a garantire un comfort interno costante, contribuiscono significativamente alla riduzione dei costi energetici, rendendo ogni edificio più eco-compatibile. Ma i benefici non finiscono qui: i pannelli coibentati sono anche resistenti al fuoco, all'umidità e ai parassiti. Questa combinazione di protezione e efficienza li rende ideali per una vasta gamma di applicazioni, dal rivestimento di edifici residenziali alla costruzione di magazzini e capannoni industriali. E se siete preoccupati per l'estetica, sappiate che i pannelli coibentati sono disponibili in una varietà di finiture e colori, per adattarsi perfettamente a qualsiasi design architettonico. Affidandovi al nostro servizio, garantiamo l'installazione professionale e la massima performance dei vostri pannelli coibentati."
    },
    lamiera:{
        title:"Lamiera",
        text:"Il tetto in lamiera rappresenta una combinazione vincente di resistenza, durata e design moderno. Questo materiale, noto per la sua robustezza e leggerezza, è una scelta eccellente per chi desidera un tetto di lunga durata che richieda una manutenzione minima. La lamiera è resistente alle intemperie, garantendo una protezione ottimale contro la pioggia, la neve e il vento. Inoltre, grazie alla sua riflettività, aiuta a mantenere gli ambienti interni freschi durante le calde giornate estive, contribuendo a ridurre i costi energetici. Ma non è solo questione di funzionalità: i tetti in lamiera sono disponibili in una vasta gamma di colori e finiture, permettendo di personalizzare l'estetica dell'edificio secondo le proprie preferenze. Che si tratti di un'abitazione moderna o di un edificio industriale, la lamiera offre soluzioni flessibili per ogni esigenza. Affidandovi al nostro servizio, garantiamo una posa in opera precisa e duratura, assicurando che il vostro tetto in lamiera sia non solo funzionale, ma anche esteticamente accattivante."
    },
    coppi:{
        title:"Coppi",
        text:"Quando si parla di tetti, i coppi rappresentano una soluzione atemporale che ha attraversato secoli, mantenendo intatta la sua reputazione di affidabilità e bellezza. Queste tegole curve, tipiche delle architetture mediterranee, sono fatte di argilla cotta, un materiale naturale che garantisce resistenza e durata nel tempo. Oltre alla loro funzionalità, i coppi conferiscono un aspetto elegante e raffinato a qualsiasi edificio, rendendolo immediatamente riconoscibile e distintivo. Ma i benefici non si fermano all'estetica. Grazie alla loro forma e composizione, i coppi offrono un eccellente isolamento termico, mantenendo gli interni freschi durante l'estate e caldi durante l'inverno. Inoltre, la loro capacità di drenare l'acqua impedisce infiltrazioni e danni strutturali. Se state considerando di rivestire il vostro tetto con coppi, potete contare sul nostro servizio per garantire una posa in opera di alta qualità, rispettando le tradizioni costruttive e offrendo le migliori soluzioni moderne."
    },
    lineevita:{
        title:"Linee vita",
        text:"Nel mondo dei lavori in quota, la sicurezza è di primaria importanza. Collaborando con Livith, rendiamo le linee vita dispositivi di protezione antica caduta essenziali per garantire che ogni intervento in altezza si svolga in condizioni di massima sicurezza. Queste strutture, ancorate al tetto o ad altre superfici elevate, consentono ai lavoratori di muoversi liberamente, avendo sempre una protezione affidabile contro possibili cadute. Oltre a garantire la sicurezza individuale, le linee vita rappresentano anche una soluzione conforme alle normative vigenti in materia di sicurezza sul lavoro. La loro installazione, eseguita in collaborazione con Livith, assicura non solo la protezione dei lavoratori ma anche la tranquillità per i proprietari di edifici e gli amministratori, offrendo sistemi all'avanguardia e certificati. Che si tratti di manutenzione, installazione o qualsiasi altro intervento in quota, è fondamentale poter contare su un sistema di sicurezza efficiente e certificato. Il nostro servizio, arricchito dalla partnership con Livith, offre la progettazione, installazione e manutenzione delle linee vita, garantendo sempre standard di sicurezza elevati e soluzioni su misura per ogni esigenza."
    },
    struttura:{
        title:"Strutture in legno",
        text:"Il legno, con la sua calda estetica e le sue proprietà naturali, è da sempre uno dei materiali preferiti nella costruzione di tetti. Le strutture in legno per tetti, come travi e listelli, combinano resistenza e flessibilità, offrendo soluzioni adattabili a qualsiasi design architettonico. L'utilizzo di listelli, in particolare, permette una distribuzione uniforme del carico sul tetto, garantendo stabilità e durata nel tempo. Questi elementi in legno, oltre a fornire supporto strutturale, favoriscono anche una corretta ventilazione, prevenendo la formazione di condensa e prolungando la vita del tetto. L'adattabilità del legno consente anche di integrare facilmente soluzioni come pannelli solari, lucernari o sistemi di raccolta delle acque piovane. Che si tratti di tetti a falda, mansarde o soluzioni più moderne, le strutture in legno offrono la possibilità di creare spazi unici e funzionali. Con il nostro servizio, garantiamo l'uso di legno di alta qualità, trattato per resistere a umidità e parassiti, assicurando una costruzione solida e duratura."
    },
    cappotto:{
        title:"Cappotto termico",
        text:"Nell'era della sostenibilità e della crescente attenzione ai consumi energetici, il cappotto termico emerge come una soluzione imprescindibile per chi desidera rendere la propria abitazione più efficiente e confortevole. Questo sistema di isolamento, applicato esternamente alle pareti dell'edificio, funge da scudo, proteggendo l'interno dagli sbalzi termici e riducendo la dispersione di calore. Il risultato? Un notevole risparmio sulle bollette, ambienti interni più confortevoli e una riduzione dell'impronta carbonica. Il cappotto termico non è solo funzionale, ma offre anche vantaggi estetici. Disponibile in una vasta gamma di finiture e colori, consente di rinnovare l'aspetto esterno dell'edificio, aggiungendo valore alla proprietà. Ma non è tutto: un buon cappotto termico contribuisce anche al benessere acustico, attenuando i rumori esterni. Se siete alla ricerca di una soluzione per migliorare l'efficienza energetica del vostro edificio, il nostro servizio offre la progettazione e installazione di cappotti termici di alta qualità, garantendo performance e durata nel tempo."
    },
    insonorizzazione:{
        title:"Isolamento acustico",
        text:"Vivere in un ambiente urbano o in zone particolarmente rumorose può diventare una sfida quando si tratta di comfort abitativo. Qui entra in gioco l'insonorizzazione, una soluzione progettata per regalare pace e tranquillità a chi desidera rifugiarsi in un'oasi di silenzio. Attraverso l'uso di materiali specifici e tecniche avanzate, l'insonorizzazione riduce significativamente la trasmissione di rumori esterni, creando un ambiente interno sereno e privo di distrazioni. Questa soluzione non è solo ideale per abitazioni situate in zone trafficate, ma è anche perfetta per studi di registrazione, uffici o qualsiasi ambiente in cui il silenzio è fondamentale. E l'insonorizzazione non si limita solo a muri e soffitti: pavimenti, porte e finestre possono essere trattati per offrire un isolamento acustico completo. Affidandovi al nostro servizio, beneficerete di un'analisi dettagliata delle vostre esigenze e di soluzioni su misura per garantire il massimo livello di insonorizzazione. Scoprite il piacere di vivere in un ambiente dove il rumore esterno rimane fuori dalla porta."
    }
}

export default paragraphs